import { NextRequest, NextResponse } from 'next/server';
import { createClient, type SupabaseServerClient } from '@/lib/supabase/server';
import { getAdminClient } from '@/lib/supabase/admin';
import { generateSanctionLetter, generateSanctionLetterFilename } from '@/lib/utils/pdf-generator';
import { calculateProcessingFee } from '@/lib/utils/calculations';
import type { SanctionLetterData, UserProfile } from '@/types';

export const runtime = 'nodejs';

async function getUserRole(supabase: SupabaseServerClient, userId: string) {
  const { data: profile } = await supabase
    .from('user_profiles')
    .select('user_id, full_name, role, organization, created_at, updated_at')
    .eq('user_id', userId)
    .maybeSingle<UserProfile>();

  return profile?.role ?? 'customer';
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { applicationId } = body;

    if (!applicationId) {
      return NextResponse.json({ error: 'applicationId is required' }, { status: 400 });
    }

    const supabase = await createClient();
    if (!supabase) {
      return NextResponse.json(
        { error: 'Supabase is not configured. Sign-in is required to generate sanction letters.' },
        { status: 401 }
      );
    }

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const role = await getUserRole(supabase, user.id);
    let applicationQuery = supabase
      .from('loan_applications')
      .select(
        'id, user_id, full_name, pan_number, phone, sanctioned_amount, interest_rate, preferred_tenure, monthly_emi, approval_status'
      )
      .eq('id', applicationId);

    if (role === 'customer') {
      applicationQuery = applicationQuery.eq('user_id', user.id);
    }

    const { data: application } = await applicationQuery.maybeSingle();
    if (!application) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }

    if (application.approval_status !== 'approved') {
      return NextResponse.json(
        { error: 'Sanction letter can only be generated for approved applications' },
        { status: 400 }
      );
    }

    const sanctionedAmount = Number(application.sanctioned_amount);
    const interestRate = Number(application.interest_rate);
    const tenure = Number(application.preferred_tenure);
    const monthlyEmi = Number(application.monthly_emi);

    if (
      !application.full_name ||
      !Number.isFinite(sanctionedAmount) ||
      !Number.isFinite(interestRate) ||
      !Number.isFinite(tenure) ||
      !Number.isFinite(monthlyEmi)
    ) {
      return NextResponse.json(
        { error: 'Application is missing sanction terms required for the letter' },
        { status: 400 }
      );
    }

    const processingFee = calculateProcessingFee(sanctionedAmount);
    const letterData: SanctionLetterData = {
      application_id: applicationId,
      customer_name: application.full_name,
      pan_number: application.pan_number || 'N/A',
      phone: application.phone || 'N/A',
      sanctioned_amount: sanctionedAmount,
      interest_rate: interestRate,
      tenure,
      monthly_emi: monthlyEmi,
      processing_fee: processingFee,
      date: new Date().toISOString(),
    };

    const pdfBuffer = await generateSanctionLetter(letterData);
    const pdfUint8 = new Uint8Array(pdfBuffer);
    const filename = generateSanctionLetterFilename(applicationId, application.full_name);

    const writeClient = getAdminClient() ?? supabase;

    await writeClient
      .from('loan_applications')
      .update({
        sanction_letter_url: `generated://${filename}`,
        application_stage: 'completed',
      })
      .eq('id', applicationId);

    const { error: documentError } = await writeClient
      .from('application_documents')
      .upsert(
        {
          application_id: applicationId,
          user_id: application.user_id,
          document_type: 'sanction_letter',
          file_name: filename,
          storage_path: `generated://${filename}`,
          status: 'verified',
          verified_at: new Date().toISOString(),
          notes: 'Generated by sanction-letter service',
        },
        { onConflict: 'application_id,document_type' }
      );

    if (documentError) {
      console.error('Document upsert error (non-critical):', documentError);
    }

    return new NextResponse(pdfUint8, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(pdfUint8.byteLength),
      },
    });
  } catch (error) {
    console.error('Document Generation Error:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate sanction letter',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    status: 'healthy',
    service: 'Document Generation API',
    timestamp: new Date().toISOString(),
    supportedFormats: ['PDF'],
  });
}
