import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { generateSanctionLetter, generateSanctionLetterFilename } from '@/lib/utils/pdf-generator';
import { calculateProcessingFee } from '@/lib/utils/calculations';
import type { SanctionLetterData, UserProfile } from '@/types';

export const runtime = 'nodejs';

async function getUserRole(supabase: Awaited<ReturnType<typeof createClient>>, userId: string) {
  const { data: profile } = await supabase
    .from('user_profiles')
    .select('user_id, full_name, role, organization, created_at, updated_at')
    .eq('user_id', userId)
    .maybeSingle<UserProfile>();

  return profile?.role ?? 'customer';
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      applicationId,
      customerName,
      panNumber,
      phone,
      sanctionedAmount,
      interestRate,
      tenure,
      monthlyEmi,
    } = body;

    if (!applicationId || !customerName || !sanctionedAmount || !interestRate || !tenure || !monthlyEmi) {
      return NextResponse.json(
        { error: 'Missing required fields for document generation' },
        { status: 400 }
      );
    }

    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const role = await getUserRole(supabase, user.id);
    let applicationQuery = supabase
      .from('loan_applications')
      .select('id, user_id, approval_status')
      .eq('id', applicationId);

    if (role === 'customer') {
      applicationQuery = applicationQuery.eq('user_id', user.id);
    }

    const { data: application } = await applicationQuery.maybeSingle();
    if (!application) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 });
    }

    const processingFee = calculateProcessingFee(sanctionedAmount);
    const letterData: SanctionLetterData = {
      application_id: applicationId,
      customer_name: customerName,
      pan_number: panNumber || 'N/A',
      phone: phone || 'N/A',
      sanctioned_amount: sanctionedAmount,
      interest_rate: interestRate,
      tenure,
      monthly_emi: monthlyEmi,
      processing_fee: processingFee,
      date: new Date().toISOString(),
    };

    const pdfBuffer = await generateSanctionLetter(letterData);
    const pdfUint8 = new Uint8Array(pdfBuffer);
    const filename = generateSanctionLetterFilename(applicationId, customerName);

    await supabase.from('loan_applications').update({
      sanction_letter_url: `generated://${filename}`,
      application_stage: 'completed',
    }).eq('id', applicationId);

    await supabase
      .from('application_documents')
      .upsert(
        {
          application_id: applicationId,
          user_id: application.user_id,
          document_type: 'sanction_letter',
          file_name: filename,
          storage_path: `generated://${filename}`,
          status: 'verified',
          verified_at: new Date().toISOString(),
          notes: 'Generated by sanction-letter service',
        },
        { onConflict: 'application_id,document_type' }
      );

    return new NextResponse(pdfUint8, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(pdfUint8.byteLength),
      },
    });
  } catch (error) {
    console.error('Document Generation Error:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate sanction letter',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    status: 'healthy',
    service: 'Document Generation API',
    timestamp: new Date().toISOString(),
    supportedFormats: ['PDF'],
  });
}
